backend/Dockerfile

Upgrade poetry to 1.0.3

---

.github/workflows/pythonpackage.yml
backend/atlas/mutations/login.py
backend/atlas/mutations/test_login.py
bors.toml

fix: Correct auth for new users

---

backend/atlas/schema/user.py
backend/atlas/utils/google.py
backend/atlas/utils/test_google.py

fix: Correct handling of missing profile in schemas

---

frontend/package-lock.json
frontend/package.json
package-lock.json
package.json

fix: Correct rrweb package location

---

backend/atlas/utils/google.py

fix: Handle missing primary attribute

---

backend/atlas/mutations/import_csv.py
frontend/src/pages/AdminImportExportPeople.js

fix: Correct departments and loading indicator on import

---

backend/atlas/models/department.py
backend/atlas/utils/google.py
frontend/src/components/Person.js
frontend/src/components/UpdatePersonForm.js
frontend/src/pages/AdminImportExportPeople.js

- correct empty department value
- #gamers -> #z-gamers
- correct counting of changes
bors r+

fix: Various small fixes

---

frontend/src/components/Person.js

ref: Remove unused team attribute

---

backend/atlas/queries/test_users.py
backend/atlas/queries/users.py
backend/atlas/schema/employeetype.py
frontend/src/components/PeopleList.js
frontend/src/pages/People.js
frontend/src/queries.js

Only execute the queries when the fields are included.
bors r+

ref: Improve query behavior for facets

---

frontend/src/pages/AdminImportExportPeople.js

fix: Correct query for export

---

backend/atlas/queries/users.py
frontend/package-lock.json
frontend/package.json
frontend/src/components/PeopleList.js
frontend/src/components/Person.js
frontend/src/pages/People.js
frontend/src/queries.js

feat: Add flexible grid to people list, and link in gamertags

---

backend/atlas/mutations/test_update_user.py
backend/atlas/utils/google.py
backend/atlas/utils/test_google.py
backend/conftest.py

ref: Better tests/logging for sync updates

---

backend/atlas/settings.py
backend/atlas/utils/google.py
frontend/src/components/UpdatePersonForm.js

ref: Improve debugability around updates

---

frontend/src/pages/OrgChart.js

fix: Correct query for orgChart

---

backend/atlas/views.py

fix: Log all graphql errors

---

frontend/src/components/PeopleList.js
frontend/src/components/Person.js
frontend/src/components/UpdatePersonForm.js

ref: Mark some email fields as hidden

---

frontend/package-lock.json
frontend/package.json
frontend/src/index.js

fix: Load @sentry/apm

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/Person.js
frontend/src/components/Person.test.js
frontend/src/pages/Login.test.js
frontend/src/setupTests.js
frontend/src/utils/testing.js

Expand test coverage for UI

---

backend/atlas/settings.py

feat: Enable Sentry logging integration

---

backend/atlas/mutations/test_update_user.py
backend/atlas/mutations/update_user.py
frontend/src/components/UpdatePersonForm.js

fix: Correct passing invalid value for department

---

frontend/src/components/Avatar.js
frontend/src/components/Header.js
frontend/src/components/PersonList.js
frontend/src/components/__snapshots__/Avatar.test.js.snap
frontend/src/pages/Home.js

This PR adds a little bit of responsive UI love to the homepage.
Before:
After:

feat(ui): Improve homepage experience on mobile devices

---

frontend/src/components/Birthday.js
frontend/src/components/FieldWrapper.js
frontend/src/components/PeopleList.js
frontend/src/components/Person.js
frontend/src/pages/People.js
frontend/src/utils/strings.js

- Add anniversary and birthday to column selection
- Add orderBy selector
bors r+

feat: Additional support for people grid

---

backend/atlas/queries/test_users.py
backend/atlas/queries/users.py
backend/conftest.py
frontend/src/pages/People.js

- Add department and team to orderBy on users query
- Add explicit order to facets returned from users
bors r+

feat: Add department and team to users orderBy

---

.github/workflows/pythonpackage.yml
backend/atlas/queries/test_users.py
backend/conftest.py
frontend/src/queries.js

fix: Missing date of birth in people export

---

.gitignore
frontend/Dockerfile
frontend/package-lock.json
frontend/package.json
package-lock.json
package.json

Getting rid of some node warnings.

ref(dependencies): Run npm audit fix

---

frontend/src/components/IconLink.js
frontend/src/components/OrgChart.js
frontend/src/components/PeopleViewSelectors.js
frontend/src/pages/People.js

I saw that zoom in/out was unimplemented so I took it on to get familiar with React.

feat(ui): Org Chart Zoom

---

.vscode/extensions.json
backend/cloudbuild.yaml
cloudbuild.yaml
frontend/cloudbuild.yaml
frontend/package-lock.json
frontend/package.json
frontend/public/index.html
frontend/src/components/FlashCard.js
frontend/src/components/Header.js
frontend/src/components/QuizCard.js
frontend/src/pages/Flashcards.js
frontend/src/pages/Quiz.js
frontend/src/routes.js
frontend/src/utils/quiz.js
frontend/src/utils/shuffle.js

A frontend-only version of a user name guessing game. The game display's the user's avatar next to four users' names (including the correct name) and lets the player make a selection with the arrow keys.
When the player makes a guess, the avatar flips over to reveal the answer. The player is rewarded with an increasing streak when they get the right answer.

feat(ui): Flashcard Game

---

backend/atlas/utils/google.py
backend/atlas/utils/test_google.py

fix: Always generate version for push updates

---

.github/workflows/pythonpackage.yml
.pre-commit-config.yaml

needed so I can actually deploy something

fix CI build

---

frontend/src/pages/Login.js

this is to test a change at canary

inherit font for login button

---

frontend/src/pages/Login.js

make google login button bold
